// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"HealthCareSystem/services"
)

type CreateUserInput struct {
	Username string            `json:"username"`
	Email    string            `json:"email"`
	Phone    string            `json:"phone"`
	Role     services.UserRole `json:"role"`
	Password string            `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type SignInInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}
